import type { WbsCategoryId, WorkUnit } from "@/constant/ledger";

/**
 * 工程領域知識庫。
 *
 * 用途：解析契約時注入對應領域的實務用語，讓模型產出的工程分項貼近
 * 監造人員實際使用的說法，而不是「基礎開挖、鋼筋組立」這類泛用詞。
 *
 * 為何需要 ——
 * 提示詞裡若只給通用範例，模型會用通用詞回答。實際的監造文件（如
 * 「水資源回收中心新建工程」第 23 次進度及品質檢討會議施工報告）顯示，
 * 分項是以「構造物單元 × 工序」組織的：不是「沉箱工程」，而是
 * 「沉箱第一單元下沉作業」「沉箱第二單元內模組立」。設備名稱也極為具體：
 * 粗攔污柵、矩型刮泥機、帶濾式脫水機、臭氧洗滌塔。
 *
 * ⚠️ 來源與可信度
 * water 領域的詞彙取自使用者提供的真實監造報告，標為 verified。
 * 其餘領域標為 ai-pending-review —— 內容為 AI 的工程領域知識，
 * 尚未以官方文件（PCCES 工項編碼、公共工程施工綱要規範、水利署技術規範）
 * 逐項查證。用字若有誤，注入提示詞後會讓模型輸出錯的分項名稱，
 * 因此請以實際契約與估驗計價單逐域審閱後再改為 verified。
 *
 * 維護方式：程式內常數，隨版本控管、可被測試。
 */

export type DomainId =
  | "water"
  | "hydraulic"
  | "waterSupply"
  | "geotech"
  | "building"
  | "road"
  | "bridge"
  | "tunnel"
  | "port"
  | "pipeline"
  | "mep"
  | "service";

/**
 * 詞彙來源。
 *
 * 誠實記錄很重要：verified 來自使用者提供的真實監造文件；
 * ai-pending-review 是 AI 領域知識、尚未經官方文件查證，可能有用字錯誤。
 */
export type Provenance = "verified" | "ai-pending-review";

export type DomainKnowledge = {
  id: DomainId;
  label: string;
  /** 用於辨識契約屬於此領域的關鍵詞（出現越多越可能）。 */
  keywords: string[];
  /** 主要構造物／設施單元。工程分項多以此為主語。 */
  structures: string[];
  /** 常見工序。與構造物交叉組成具體分項。 */
  sequences: string[];
  /** 主要設備／材料，多需送審與檢驗。 */
  equipment: string[];
  /** 內容來源，供審閱時判斷可信度。 */
  provenance: Provenance;
  /**
   * 參考工程分項：實務上會出現的完整分項名稱，附計量單位與 WBS 類別。
   *
   * 與 structures／sequences 的差別是「已組合完成」——
   * 可直接對照，注入時依契約內文挑相關者（見 domain-match）。
   */
  workItems: ReferenceWorkItem[];
};

/**
 * 一項參考工程分項。
 *
 * 帶單位與類別的理由 ——
 * 工程分項在估驗台帳上就是一列價目：沒有單位就無法計量，
 * 沒有 WBS 類別就無法彙整成「土建做了幾成、機電做了幾成」。
 * 只有名稱時，模型解讀契約也只能吐出一串名字，
 * 使用者仍得逐項回頭補單位。
 *
 * 單位與類別由規則推斷（依名稱關鍵詞，落空時取領域慣用預設），
 * 尚未逐項查證，請見 docs/知識庫審閱清單.md。
 */
export type ReferenceWorkItem = {
  name: string;
  /** 計量單位，如 m3、m、組、式（見 constant/ledger 的 WORK_UNITS）。 */
  unit: WorkUnit;
  /** WBS 類別 id（見 constant/ledger 的 WBS_CATEGORIES）。 */
  wbs: WbsCategoryId;
};

export const DOMAINS: DomainKnowledge[] = [
  {
    id: "water",
    label: "污水下水道與水資源回收",
    keywords: [
      "污水下水道",
      "水資源回收中心",
      "污水處理",
      "水再生",
      "用戶接管",
      "抽水站",
      "放流",
      "污泥",
    ],
    structures: [
      "進流抽水站",
      "細部處理單元",
      "初沉池",
      "二沉池",
      "曝氣池",
      "消毒池",
      "污泥濃縮池",
      "脫水機房",
      "聯合機房",
      "鼓風機房",
      "配電室",
      "放流口",
      "沉箱",
      "管理中心",
    ],
    sequences: [
      "地盤改良",
      "基樁施作",
      "沉箱下沉作業",
      "內模組立",
      "外模組立",
      "鋼筋綁紮",
      "鋼筋續接器安裝",
      "混凝土澆置",
      "防水施作",
      "管線埋設",
      "預鑄人孔安裝",
      "設備安裝",
      "管線試壓",
      "功能試車",
      "滿水試驗",
    ],
    equipment: [
      "粗攔污柵",
      "細攔污柵",
      "沉水式泵浦",
      "初沉污泥泵",
      "矩型刮泥機",
      "洗砂機",
      "浮渣分離機",
      "帶濾式脫水機",
      "臭氧洗滌塔",
      "鼓風機",
      "閘門",
      "柴油引擎發電機",
      "不鏽鋼管及管件",
      "導線管",
    ],
    provenance: "verified",
    workItems: [
      { name: "進流抽水站基礎開挖", unit: "m3", wbs: "civil" },
      { name: "進流抽水站連續壁施作", unit: "m2", wbs: "civil" },
      { name: "進流抽水站底版澆置", unit: "m3", wbs: "civil" },
      { name: "進流抽水站牆體澆置", unit: "m3", wbs: "civil" },
      { name: "沉箱第一單元製作", unit: "座", wbs: "civil" },
      { name: "沉箱第一單元下沉作業", unit: "座", wbs: "civil" },
      { name: "沉箱第二單元製作", unit: "座", wbs: "civil" },
      { name: "沉箱第二單元內模組立", unit: "m2", wbs: "civil" },
      { name: "沉箱刃口製作", unit: "座", wbs: "civil" },
      { name: "沉箱封底混凝土澆置", unit: "m3", wbs: "civil" },
      { name: "沉箱頂版澆置", unit: "m3", wbs: "civil" },
      { name: "沉箱鋼筋續接器安裝", unit: "座", wbs: "civil" },
      { name: "粗攔污柵設備安裝", unit: "組", wbs: "mechanical" },
      { name: "細攔污柵設備安裝", unit: "組", wbs: "mechanical" },
      { name: "沉砂池結構澆置", unit: "m3", wbs: "civil" },
      { name: "洗砂機安裝", unit: "組", wbs: "mechanical" },
      { name: "初沉池結構開挖", unit: "m3", wbs: "civil" },
      { name: "初沉池底版澆置", unit: "m3", wbs: "civil" },
      { name: "初沉池刮泥機安裝", unit: "組", wbs: "mechanical" },
      { name: "初沉池污泥泵安裝", unit: "組", wbs: "mechanical" },
      { name: "曝氣池結構澆置", unit: "m3", wbs: "mechanical" },
      { name: "曝氣池曝氣盤安裝", unit: "組", wbs: "mechanical" },
      { name: "曝氣池隔牆施作", unit: "m2", wbs: "mechanical" },
      { name: "鼓風機房結構澆置", unit: "m3", wbs: "mechanical" },
      { name: "鼓風機安裝", unit: "組", wbs: "mechanical" },
      { name: "鼓風機管路配置", unit: "m", wbs: "mechanical" },
      { name: "二沉池結構澆置", unit: "m3", wbs: "civil" },
      { name: "二沉池刮泥機安裝", unit: "組", wbs: "mechanical" },
      { name: "二沉池溢流堰施作", unit: "座", wbs: "civil" },
      { name: "消毒池結構澆置", unit: "m3", wbs: "civil" },
      { name: "紫外線消毒設備安裝", unit: "組", wbs: "mechanical" },
      { name: "加氯設備安裝", unit: "組", wbs: "mechanical" },
      { name: "污泥濃縮池結構澆置", unit: "m3", wbs: "civil" },
      { name: "污泥濃縮機安裝", unit: "組", wbs: "mechanical" },
      { name: "污泥消化池結構澆置", unit: "m3", wbs: "civil" },
      { name: "帶濾式脫水機安裝", unit: "組", wbs: "mechanical" },
      { name: "脫水機房結構澆置", unit: "m3", wbs: "mechanical" },
      { name: "脫水機房吊車安裝", unit: "座", wbs: "mechanical" },
      { name: "污泥餅輸送設備安裝", unit: "組", wbs: "mechanical" },
      { name: "浮渣分離機安裝", unit: "組", wbs: "mechanical" },
      { name: "臭氧洗滌塔安裝", unit: "組", wbs: "mechanical" },
      { name: "除臭風管配置", unit: "m3", wbs: "pipeline" },
      { name: "生物除臭設備安裝", unit: "組", wbs: "mechanical" },
      { name: "聯合機房地盤改良", unit: "m3", wbs: "civil" },
      { name: "聯合機房基樁施作", unit: "支", wbs: "civil" },
      { name: "聯合機房結構澆置", unit: "m3", wbs: "civil" },
      { name: "配電室結構澆置", unit: "m3", wbs: "electrical" },
      { name: "配電盤安裝", unit: "組", wbs: "electrical" },
      { name: "柴油引擎發電機安裝", unit: "組", wbs: "electrical" },
      { name: "受電設備安裝", unit: "組", wbs: "electrical" },
      { name: "中央監控系統建置", unit: "式", wbs: "electrical" },
      { name: "儀控盤安裝", unit: "組", wbs: "electrical" },
      { name: "現場儀器安裝", unit: "組", wbs: "electrical" },
      { name: "流量計安裝", unit: "組", wbs: "electrical" },
      { name: "水質監測設備安裝", unit: "組", wbs: "mechanical" },
      { name: "放流口結構施作", unit: "座", wbs: "civil" },
      { name: "放流管線埋設", unit: "m", wbs: "pipeline" },
      { name: "放流水質採樣設施", unit: "組", wbs: "civil" },
      { name: "廠內道路舖築", unit: "m2", wbs: "civil" },
      { name: "廠區圍牆施作", unit: "m2", wbs: "civil" },
      { name: "廠區排水施作", unit: "m", wbs: "civil" },
      { name: "廠區景觀綠化", unit: "m2", wbs: "civil" },
      { name: "管理中心結構澆置", unit: "m3", wbs: "pipeline" },
      { name: "管理中心裝修", unit: "m2", wbs: "pipeline" },
      { name: "不鏽鋼管及管件安裝", unit: "m", wbs: "pipeline" },
      { name: "導線管配置", unit: "m", wbs: "electrical" },
      { name: "閘門設備安裝", unit: "座", wbs: "mechanical" },
      { name: "電動閥安裝", unit: "組", wbs: "mechanical" },
      { name: "沉水式泵浦安裝", unit: "組", wbs: "mechanical" },
      { name: "加壓泵浦安裝", unit: "組", wbs: "mechanical" },
      { name: "管線水壓試驗", unit: "式", wbs: "pipeline" },
      { name: "池體滿水試驗", unit: "式", wbs: "civil" },
      { name: "單機功能試車", unit: "式", wbs: "civil" },
      { name: "系統整體試車", unit: "式", wbs: "civil" },
      { name: "處理效能驗證", unit: "式", wbs: "civil" },
      { name: "操作維護訓練", unit: "式", wbs: "indirect" },
      { name: "用戶接管幹管埋設", unit: "m", wbs: "pipeline" },
      { name: "用戶接管分支管埋設", unit: "m", wbs: "pipeline" },
      { name: "用戶接管人孔施作", unit: "座", wbs: "pipeline" },
      { name: "現有管線遷移", unit: "m", wbs: "pipeline" },
    ],
  },
  {
    id: "hydraulic",
    label: "河川與水利工程",
    keywords: [
      "河川",
      "堤防",
      "護岸",
      "疏浚",
      "滯洪",
      "水門",
      "排水改善",
      "治理",
      "野溪",
      "水庫",
      "攔河堰",
      "防砂",
    ],
    structures: [
      "堤防",
      "護岸",
      "丁壩",
      "固床工",
      "水門",
      "滯洪池",
      "攔河堰",
      "導水路",
      "渠道",
      "防砂壩",
      "溢洪道",
    ],
    sequences: [
      "河道疏浚",
      "土堤填築",
      "混凝土護坡澆置",
      "砌石護岸施作",
      "閘門安裝",
      "渠道襯砌",
      "壩體填築",
      "清淤作業",
    ],
    equipment: [
      "抽水機組",
      "啟閉設備",
      "自動水門",
      "水位計",
      "雨量站",
      "遙測系統",
      "蛇籠",
      "石籠",
    ],
    provenance: "ai-pending-review",
    workItems: [
      { name: "河川斷面測量", unit: "m", wbs: "indirect" },
      { name: "河道疏浚", unit: "m3", wbs: "civil" },
      { name: "河道拓寬開挖", unit: "m3", wbs: "civil" },
      { name: "土方運棄", unit: "m3", wbs: "civil" },
      { name: "堤防基礎開挖", unit: "m3", wbs: "civil" },
      { name: "堤防土堤填築", unit: "m3", wbs: "civil" },
      { name: "堤防混凝土基腳澆置", unit: "m3", wbs: "civil" },
      { name: "堤防護坡砌石", unit: "m2", wbs: "civil" },
      { name: "堤防混凝土護坡澆置", unit: "m3", wbs: "civil" },
      { name: "堤防頂道路舖築", unit: "m2", wbs: "civil" },
      { name: "堤頂欄杆設置", unit: "m", wbs: "civil" },
      { name: "堤防植生綠化", unit: "m2", wbs: "civil" },
      { name: "防汛道路施作", unit: "m", wbs: "civil" },
      { name: "越堤道路施作", unit: "m", wbs: "civil" },
      { name: "堤防伸縮縫施作", unit: "m", wbs: "civil" },
      { name: "堤防排水孔設置", unit: "m", wbs: "civil" },
      { name: "丁壩工施作", unit: "座", wbs: "civil" },
      { name: "固床工施作", unit: "座", wbs: "civil" },
      { name: "潛壩施作", unit: "座", wbs: "civil" },
      { name: "護岸基礎拋石", unit: "m3", wbs: "civil" },
      { name: "蛇籠護岸施作", unit: "m", wbs: "civil" },
      { name: "石籠護岸施作", unit: "m", wbs: "civil" },
      { name: "混凝土框護岸施作", unit: "m3", wbs: "civil" },
      { name: "生態砌石護岸", unit: "m", wbs: "civil" },
      { name: "排水路襯砌施作", unit: "m", wbs: "civil" },
      { name: "排水路箱涵澆置", unit: "m3", wbs: "pipeline" },
      { name: "排水路清淤", unit: "m3", wbs: "civil" },
      { name: "排水溝渠改善", unit: "m", wbs: "pipeline" },
      { name: "抽水站廠房結構澆置", unit: "m3", wbs: "civil" },
      { name: "抽水站前池施作", unit: "座", wbs: "civil" },
      { name: "抽水站進水渠道施作", unit: "m", wbs: "pipeline" },
      { name: "抽水機組安裝", unit: "組", wbs: "mechanical" },
      { name: "抽水站出水池施作", unit: "座", wbs: "civil" },
      { name: "抽水站閘門安裝", unit: "座", wbs: "mechanical" },
      { name: "抽水站配電設備安裝", unit: "座", wbs: "electrical" },
      { name: "抽水站試運轉", unit: "座", wbs: "civil" },
      { name: "水門結構施作", unit: "座", wbs: "mechanical" },
      { name: "水門啟閉設備安裝", unit: "座", wbs: "mechanical" },
      { name: "自動水門設置", unit: "座", wbs: "mechanical" },
      { name: "防潮閘門安裝", unit: "座", wbs: "mechanical" },
      { name: "滯洪池開挖", unit: "m3", wbs: "civil" },
      { name: "滯洪池護坡施作", unit: "m3", wbs: "civil" },
      { name: "滯洪池進出水口施作", unit: "m3", wbs: "civil" },
      { name: "滯洪池溢流堰施作", unit: "m3", wbs: "civil" },
      { name: "雨水滯留設施施作", unit: "m3", wbs: "pipeline" },
      { name: "透水舖面施作", unit: "m2", wbs: "civil" },
      { name: "貯留滲透設施施作", unit: "m3", wbs: "civil" },
      { name: "生態池施作", unit: "m3", wbs: "civil" },
      { name: "攔河堰結構施作", unit: "座", wbs: "civil" },
      { name: "攔河堰閘門安裝", unit: "座", wbs: "mechanical" },
      { name: "沉砂池施作", unit: "m3", wbs: "civil" },
      { name: "進水口結構施作", unit: "座", wbs: "civil" },
      { name: "導水路襯砌施作", unit: "m", wbs: "pipeline" },
      { name: "導水隧道開挖", unit: "m3", wbs: "pipeline" },
      { name: "渠道混凝土襯砌", unit: "m3", wbs: "pipeline" },
      { name: "渡槽結構施作", unit: "座", wbs: "civil" },
      { name: "倒虹吸工施作", unit: "座", wbs: "civil" },
      { name: "分水工施作", unit: "座", wbs: "civil" },
      { name: "量水設施設置", unit: "組", wbs: "civil" },
      { name: "渠道防滲處理", unit: "m", wbs: "pipeline" },
      { name: "水庫壩體填築", unit: "m3", wbs: "civil" },
      { name: "壩體止水處理", unit: "m3", wbs: "civil" },
      { name: "溢洪道結構施作", unit: "座", wbs: "civil" },
      { name: "排砂道施作", unit: "座", wbs: "civil" },
      { name: "取水工結構施作", unit: "座", wbs: "civil" },
      { name: "水庫清淤作業", unit: "m3", wbs: "civil" },
      { name: "水情自動測報系統建置", unit: "式", wbs: "electrical" },
      { name: "水位計設置", unit: "組", wbs: "electrical" },
      { name: "雨量站設置", unit: "組", wbs: "electrical" },
      { name: "遙測系統建置", unit: "式", wbs: "electrical" },
      { name: "防砂壩施作", unit: "座", wbs: "civil" },
      { name: "潛壩群施作", unit: "座", wbs: "civil" },
      { name: "野溪整治護岸", unit: "m", wbs: "civil" },
      { name: "坡地排水施作", unit: "m", wbs: "civil" },
      { name: "沉砂滯洪設施施作", unit: "m3", wbs: "civil" },
      { name: "土石流防治設施施作", unit: "m3", wbs: "civil" },
    ],
  },
  {
    id: "waterSupply",
    label: "自來水工程",
    keywords: [
      "自來水",
      "淨水場",
      "配水",
      "送水",
      "清水池",
      "取水",
      "供水",
      "管網",
      "水表",
    ],
    structures: [
      "取水井",
      "淨水場",
      "沉澱池",
      "快濾池",
      "清水池",
      "配水池",
      "加壓站",
    ],
    sequences: [
      "濾料舖設",
      "管線推進工法施作",
      "鋼管熔接施作",
      "管線消毒沖洗",
      "管網分區計量設置",
    ],
    equipment: [
      "加藥設備",
      "送水泵浦",
      "制水閥",
      "排氣閥",
      "水表",
      "延性鑄鐵管",
      "水質線上監測",
    ],
    provenance: "ai-pending-review",
    workItems: [
      { name: "取水井施作", unit: "座", wbs: "pipeline" },
      { name: "取水管線埋設", unit: "m", wbs: "pipeline" },
      { name: "原水抽水站施作", unit: "座", wbs: "pipeline" },
      { name: "原水管線埋設", unit: "m", wbs: "pipeline" },
      { name: "淨水場快混池施作", unit: "m3", wbs: "pipeline" },
      { name: "淨水場膠凝池施作", unit: "m3", wbs: "pipeline" },
      { name: "沉澱池結構澆置", unit: "m3", wbs: "civil" },
      { name: "快濾池結構澆置", unit: "m3", wbs: "civil" },
      { name: "濾料舖設", unit: "m2", wbs: "pipeline" },
      { name: "濾網更換", unit: "組", wbs: "mechanical" },
      { name: "加藥設備安裝", unit: "組", wbs: "mechanical" },
      { name: "加藥管路配置", unit: "m", wbs: "pipeline" },
      { name: "清水池結構澆置", unit: "m3", wbs: "civil" },
      { name: "清水池防水施作", unit: "m2", wbs: "pipeline" },
      { name: "清水池滿水試驗", unit: "座", wbs: "pipeline" },
      { name: "配水池結構澆置", unit: "m3", wbs: "civil" },
      { name: "送水抽水站施作", unit: "座", wbs: "pipeline" },
      { name: "送水泵浦安裝", unit: "組", wbs: "mechanical" },
      { name: "加壓站結構施作", unit: "座", wbs: "civil" },
      { name: "加壓設備安裝", unit: "組", wbs: "mechanical" },
      { name: "配水幹管埋設", unit: "m", wbs: "pipeline" },
      { name: "配水支管埋設", unit: "m", wbs: "pipeline" },
      { name: "接戶管施作", unit: "m", wbs: "pipeline" },
      { name: "水表箱設置", unit: "座", wbs: "pipeline" },
      { name: "消防栓設置", unit: "座", wbs: "mechanical" },
      { name: "制水閥設置", unit: "組", wbs: "mechanical" },
      { name: "排氣閥設置", unit: "組", wbs: "mechanical" },
      { name: "排水閥設置", unit: "組", wbs: "mechanical" },
      { name: "管線推進工法施作", unit: "m", wbs: "pipeline" },
      { name: "管線鑽掘工法施作", unit: "m", wbs: "pipeline" },
      { name: "鋼管熔接施作", unit: "m", wbs: "pipeline" },
      { name: "延性鑄鐵管接合", unit: "m", wbs: "pipeline" },
      { name: "管線內襯修補", unit: "m2", wbs: "pipeline" },
      { name: "管線更新汰換", unit: "m", wbs: "pipeline" },
      { name: "漏水偵測作業", unit: "組", wbs: "electrical" },
      { name: "管網分區計量設置", unit: "組", wbs: "electrical" },
      { name: "管線水壓試驗", unit: "式", wbs: "pipeline" },
      { name: "管線消毒沖洗", unit: "m", wbs: "pipeline" },
      { name: "水質檢驗採樣", unit: "m", wbs: "pipeline" },
      { name: "供水系統切換", unit: "式", wbs: "pipeline" },
      { name: "淨水場自動控制建置", unit: "式", wbs: "electrical" },
      { name: "水質線上監測設置", unit: "式", wbs: "pipeline" },
      { name: "污泥處理設施施作", unit: "m", wbs: "pipeline" },
      { name: "回收水設施施作", unit: "m", wbs: "pipeline" },
    ],
  },
  {
    id: "geotech",
    label: "大地與基礎工程",
    keywords: [
      "地盤改良",
      "連續壁",
      "基樁",
      "擋土",
      "邊坡",
      "支撐",
      "地錨",
      "鑽探",
    ],
    structures: [
      "連續壁",
      "場鑄樁",
      "鋼板樁",
      "擋土牆",
      "內支撐",
      "地錨",
      "邊坡格樑",
    ],
    sequences: [
      "攪拌樁地盤改良",
      "高壓噴射灌漿",
      "化學灌漿施作",
      "連續壁單元開挖",
      "基樁載重試驗",
      "噴凝土護坡施作",
    ],
    equipment: [
      "土壓力計",
      "傾度管",
      "水壓計",
      "沉陷觀測點",
      "落石防護網",
    ],
    provenance: "ai-pending-review",
    workItems: [
      { name: "地質鑽探調查", unit: "m3", wbs: "civil" },
      { name: "地下水位觀測井設置", unit: "座", wbs: "civil" },
      { name: "標準貫入試驗", unit: "式", wbs: "civil" },
      { name: "地盤改良試驗", unit: "m3", wbs: "civil" },
      { name: "攪拌樁地盤改良", unit: "m3", wbs: "mechanical" },
      { name: "高壓噴射灌漿", unit: "m3", wbs: "civil" },
      { name: "化學灌漿施作", unit: "m3", wbs: "civil" },
      { name: "排水帶施作", unit: "m3", wbs: "civil" },
      { name: "預壓載重工法施作", unit: "m3", wbs: "civil" },
      { name: "置換工法施作", unit: "m3", wbs: "civil" },
      { name: "夯實地盤改良", unit: "m3", wbs: "civil" },
      { name: "地盤改良鑽心取樣", unit: "m3", wbs: "civil" },
      { name: "連續壁導溝施作", unit: "m2", wbs: "pipeline" },
      { name: "連續壁單元開挖", unit: "m3", wbs: "civil" },
      { name: "連續壁鋼筋籠吊放", unit: "m2", wbs: "civil" },
      { name: "連續壁混凝土澆置", unit: "m3", wbs: "civil" },
      { name: "連續壁墊層施作", unit: "m2", wbs: "civil" },
      { name: "鋼板樁打設", unit: "t", wbs: "civil" },
      { name: "鋼板樁拔除", unit: "t", wbs: "civil" },
      { name: "排樁施作", unit: "支", wbs: "civil" },
      { name: "場鑄樁施作", unit: "支", wbs: "civil" },
      { name: "預鑄樁打設", unit: "支", wbs: "civil" },
      { name: "鋼管樁打設", unit: "支", wbs: "pipeline" },
      { name: "微型樁施作", unit: "支", wbs: "civil" },
      { name: "基樁載重試驗", unit: "支", wbs: "civil" },
      { name: "基樁完整性試驗", unit: "支", wbs: "civil" },
      { name: "樁頭處理", unit: "支", wbs: "civil" },
      { name: "基礎版澆置", unit: "m3", wbs: "civil" },
      { name: "內支撐架設", unit: "m3", wbs: "civil" },
      { name: "內支撐拆除", unit: "式", wbs: "civil" },
      { name: "地錨施作", unit: "m", wbs: "civil" },
      { name: "地錨拉拔試驗", unit: "m", wbs: "civil" },
      { name: "擋土支撐系統施作", unit: "式", wbs: "civil" },
      { name: "安全支撐監測", unit: "m3", wbs: "civil" },
      { name: "土壓力計設置", unit: "式", wbs: "civil" },
      { name: "傾度管設置", unit: "式", wbs: "pipeline" },
      { name: "水壓計設置", unit: "式", wbs: "civil" },
      { name: "沉陷觀測點設置", unit: "式", wbs: "civil" },
      { name: "鄰房監測作業", unit: "月", wbs: "civil" },
      { name: "開挖面湧水處理", unit: "m3", wbs: "civil" },
      { name: "邊坡整坡作業", unit: "m2", wbs: "civil" },
      { name: "邊坡格樑施作", unit: "m", wbs: "civil" },
      { name: "噴凝土護坡施作", unit: "m2", wbs: "civil" },
      { name: "打樁植生施作", unit: "m2", wbs: "civil" },
      { name: "邊坡排水管施作", unit: "m", wbs: "pipeline" },
      { name: "截水溝施作", unit: "m", wbs: "pipeline" },
      { name: "落石防護網設置", unit: "式", wbs: "civil" },
      { name: "擋土牆施作", unit: "m3", wbs: "civil" },
    ],
  },
  {
    id: "building",
    label: "建築工程",
    keywords: [
      "新建工程",
      "建築",
      "廠房",
      "辦公廳舍",
      "校舍",
      "增建",
      "工程建造",
    ],
    structures: [
      "基礎",
      "地下室",
      "結構主體",
      "屋頂",
      "外牆",
      "機電空間",
    ],
    sequences: [
      "整地",
      "擋土支撐",
      "開挖",
      "基礎施作",
      "鋼筋綁紮",
      "模板組立",
      "混凝土澆置",
      "鋼構吊裝",
      "外牆施作",
      "防水施作",
      "裝修",
      "機電安裝",
    ],
    equipment: [
      "電梯",
      "空調主機",
      "配電盤",
      "消防設備",
      "給排水設備",
    ],
    provenance: "ai-pending-review",
    workItems: [
      { name: "工地整地作業", unit: "月", wbs: "civil" },
      { name: "假設工程施作", unit: "式", wbs: "indirect" },
      { name: "工程圍籬設置", unit: "m", wbs: "safety" },
      { name: "臨時道路施作", unit: "m2", wbs: "safety" },
      { name: "放樣作業", unit: "月", wbs: "indirect" },
      { name: "基礎開挖", unit: "m3", wbs: "civil" },
      { name: "基礎混凝土澆置", unit: "m3", wbs: "civil" },
      { name: "地下室外牆澆置", unit: "m3", wbs: "civil" },
      { name: "地下室底版澆置", unit: "m3", wbs: "civil" },
      { name: "筏式基礎施作", unit: "m3", wbs: "civil" },
      { name: "柱鋼筋綁紮", unit: "t", wbs: "civil" },
      { name: "梁鋼筋綁紮", unit: "t", wbs: "civil" },
      { name: "樓版鋼筋綁紮", unit: "t", wbs: "civil" },
      { name: "牆體鋼筋綁紮", unit: "m3", wbs: "civil" },
      { name: "柱模板組立", unit: "m2", wbs: "civil" },
      { name: "梁模板組立", unit: "m2", wbs: "civil" },
      { name: "樓版模板組立", unit: "m2", wbs: "civil" },
      { name: "模板拆除", unit: "式", wbs: "civil" },
      { name: "柱混凝土澆置", unit: "m3", wbs: "civil" },
      { name: "梁版混凝土澆置", unit: "m3", wbs: "civil" },
      { name: "剪力牆澆置", unit: "m3", wbs: "civil" },
      { name: "樓梯結構澆置", unit: "m3", wbs: "civil" },
      { name: "鋼骨柱吊裝", unit: "m2", wbs: "civil" },
      { name: "鋼骨梁吊裝", unit: "m2", wbs: "civil" },
      { name: "鋼構銲接施作", unit: "t", wbs: "civil" },
      { name: "鋼構栓接施作", unit: "t", wbs: "civil" },
      { name: "鋼構防火被覆施作", unit: "m2", wbs: "civil" },
      { name: "樓承板舖設", unit: "m", wbs: "civil" },
      { name: "屋頂結構澆置", unit: "m3", wbs: "civil" },
      { name: "屋頂防水施作", unit: "m2", wbs: "civil" },
      { name: "屋頂隔熱施作", unit: "m2", wbs: "civil" },
      { name: "外牆磁磚黏貼", unit: "m2", wbs: "civil" },
      { name: "外牆帷幕安裝", unit: "m2", wbs: "civil" },
      { name: "外牆石材乾掛", unit: "m2", wbs: "civil" },
      { name: "外牆油漆粉刷", unit: "m2", wbs: "civil" },
      { name: "門窗框安裝", unit: "m2", wbs: "civil" },
      { name: "門窗玻璃安裝", unit: "m2", wbs: "civil" },
      { name: "室內隔間牆施作", unit: "m2", wbs: "civil" },
      { name: "天花板施作", unit: "m2", wbs: "civil" },
      { name: "地坪粉光施作", unit: "m2", wbs: "civil" },
      { name: "地坪磁磚舖貼", unit: "m2", wbs: "civil" },
      { name: "室內油漆粉刷", unit: "m2", wbs: "civil" },
      { name: "衛浴設備安裝", unit: "組", wbs: "mechanical" },
      { name: "廚具安裝", unit: "m2", wbs: "civil" },
      { name: "電梯機坑施作", unit: "組", wbs: "mechanical" },
      { name: "電梯導軌安裝", unit: "組", wbs: "mechanical" },
      { name: "電梯機廂安裝", unit: "組", wbs: "mechanical" },
      { name: "無障礙設施施作", unit: "m2", wbs: "civil" },
      { name: "給水管線配置", unit: "m2", wbs: "pipeline" },
      { name: "排水管線配置", unit: "m2", wbs: "pipeline" },
      { name: "衛生設備安裝", unit: "組", wbs: "mechanical" },
      { name: "消防撒水管配置", unit: "m2", wbs: "mechanical" },
      { name: "消防栓箱安裝", unit: "座", wbs: "mechanical" },
      { name: "火警受信總機安裝", unit: "組", wbs: "mechanical" },
      { name: "排煙設備安裝", unit: "組", wbs: "mechanical" },
      { name: "空調風管施作", unit: "組", wbs: "mechanical" },
      { name: "空調主機安裝", unit: "組", wbs: "mechanical" },
      { name: "冷卻水塔安裝", unit: "組", wbs: "mechanical" },
      { name: "配電盤安裝", unit: "組", wbs: "electrical" },
      { name: "電力幹線配線", unit: "m", wbs: "electrical" },
      { name: "弱電系統配線", unit: "m", wbs: "electrical" },
      { name: "接地系統施作", unit: "式", wbs: "electrical" },
      { name: "太陽光電設施安裝", unit: "m2", wbs: "civil" },
      { name: "景觀植栽施作", unit: "m2", wbs: "civil" },
    ],
  },
  {
    id: "road",
    label: "道路與排水",
    keywords: [
      "道路",
      "拓寬",
      "路面",
      "人行道",
      "側溝",
      "排水改善",
    ],
    structures: [
      "路基",
      "路面",
      "人行道",
      "側溝",
      "涵管",
      "號誌",
    ],
    sequences: [
      "路面刨除",
      "管線遷移",
      "路基整理",
      "級配舖築",
      "瀝青混凝土舖築",
      "側溝施作",
      "標線繪設",
      "道路復舊",
    ],
    equipment: [
      "伸縮縫",
      "號誌設備",
      "照明燈具",
    ],
    provenance: "ai-pending-review",
    workItems: [
      { name: "道路中心線放樣", unit: "m", wbs: "indirect" },
      { name: "路權範圍測量", unit: "式", wbs: "indirect" },
      { name: "既有路面刨除", unit: "m2", wbs: "civil" },
      { name: "既有結構物拆除", unit: "式", wbs: "civil" },
      { name: "管線遷移協調", unit: "式", wbs: "indirect" },
      { name: "管線遷移施作", unit: "m", wbs: "pipeline" },
      { name: "路基整理夯實", unit: "m2", wbs: "civil" },
      { name: "路床整理", unit: "m2", wbs: "civil" },
      { name: "不良路基換填", unit: "m2", wbs: "civil" },
      { name: "級配底層舖築", unit: "m3", wbs: "civil" },
      { name: "級配基層舖築", unit: "m3", wbs: "civil" },
      { name: "瀝青混凝土底層舖築", unit: "m3", wbs: "civil" },
      { name: "瀝青混凝土面層舖築", unit: "m2", wbs: "civil" },
      { name: "透層舖灑", unit: "m", wbs: "civil" },
      { name: "黏層舖灑", unit: "m", wbs: "civil" },
      { name: "路面接縫處理", unit: "m2", wbs: "civil" },
      { name: "混凝土路面澆置", unit: "m2", wbs: "civil" },
      { name: "混凝土路面切縫", unit: "m2", wbs: "civil" },
      { name: "路面回饋帶施作", unit: "m2", wbs: "civil" },
      { name: "路面高程檢測", unit: "m2", wbs: "civil" },
      { name: "路肩施作", unit: "m", wbs: "civil" },
      { name: "中央分隔島施作", unit: "m", wbs: "civil" },
      { name: "分隔島植栽", unit: "m2", wbs: "civil" },
      { name: "人行道基礎施作", unit: "m3", wbs: "civil" },
      { name: "人行道磚舖設", unit: "m", wbs: "civil" },
      { name: "人行道無障礙斜坡", unit: "m", wbs: "civil" },
      { name: "導盲磚舖設", unit: "m", wbs: "civil" },
      { name: "路緣石設置", unit: "式", wbs: "civil" },
      { name: "側溝基礎施作", unit: "m3", wbs: "pipeline" },
      { name: "L 型側溝施作", unit: "m", wbs: "pipeline" },
      { name: "U 型側溝施作", unit: "m", wbs: "pipeline" },
      { name: "集水井施作", unit: "座", wbs: "civil" },
      { name: "雨水陰井施作", unit: "座", wbs: "pipeline" },
      { name: "涵管埋設", unit: "m", wbs: "pipeline" },
      { name: "箱涵澆置", unit: "m3", wbs: "pipeline" },
      { name: "涵洞進出口整理", unit: "座", wbs: "pipeline" },
      { name: "邊溝清淤", unit: "m3", wbs: "pipeline" },
      { name: "路面標線繪設", unit: "m2", wbs: "civil" },
      { name: "標線刨除", unit: "m2", wbs: "civil" },
      { name: "反光標記設置", unit: "式", wbs: "civil" },
      { name: "交通標誌牌面製作", unit: "座", wbs: "civil" },
      { name: "交通標誌桿設置", unit: "座", wbs: "civil" },
      { name: "號誌桿基礎施作", unit: "m3", wbs: "electrical" },
      { name: "號誌燈具安裝", unit: "座", wbs: "electrical" },
      { name: "號誌控制器安裝", unit: "座", wbs: "electrical" },
      { name: "行人專用號誌安裝", unit: "座", wbs: "electrical" },
      { name: "路燈基礎施作", unit: "m3", wbs: "civil" },
      { name: "路燈桿設置", unit: "座", wbs: "civil" },
      { name: "路燈燈具安裝", unit: "座", wbs: "civil" },
      { name: "照明電纜配線", unit: "m", wbs: "electrical" },
      { name: "監視系統設置", unit: "組", wbs: "electrical" },
      { name: "測速設備設置", unit: "式", wbs: "civil" },
      { name: "護欄設置", unit: "m", wbs: "civil" },
      { name: "防眩板設置", unit: "式", wbs: "civil" },
      { name: "道路植栽", unit: "m2", wbs: "civil" },
      { name: "道路復舊", unit: "m", wbs: "civil" },
    ],
  },
  {
    id: "bridge",
    label: "橋梁工程",
    keywords: [
      "橋梁",
      "跨橋",
      "陸橋",
      "橋台",
      "橋墩",
    ],
    structures: [
      "橋台",
      "橋墩",
      "基樁",
      "上部結構",
      "橋面版",
      "支承",
    ],
    sequences: [
      "基樁施作",
      "橋台施作",
      "橋墩施作",
      "預力梁製作",
      "吊梁作業",
      "橋面版澆置",
      "伸縮縫安裝",
      "載重試驗",
    ],
    equipment: [
      "支承墊",
      "伸縮縫",
      "預力鋼腱",
    ],
    provenance: "ai-pending-review",
    workItems: [
      { name: "橋位測量放樣", unit: "式", wbs: "indirect" },
      { name: "便橋施作", unit: "m3", wbs: "civil" },
      { name: "臨時擋水設施施作", unit: "m3", wbs: "safety" },
      { name: "河道臨時導流", unit: "m", wbs: "safety" },
      { name: "橋台基礎開挖", unit: "m3", wbs: "civil" },
      { name: "橋台基樁施作", unit: "支", wbs: "civil" },
      { name: "橋台帽梁澆置", unit: "m3", wbs: "civil" },
      { name: "橋台背牆澆置", unit: "m3", wbs: "civil" },
      { name: "橋台翼牆澆置", unit: "m3", wbs: "civil" },
      { name: "橋台背填施作", unit: "座", wbs: "civil" },
      { name: "橋墩基礎開挖", unit: "m3", wbs: "civil" },
      { name: "橋墩基樁施作", unit: "支", wbs: "civil" },
      { name: "橋墩井式基礎施作", unit: "m3", wbs: "civil" },
      { name: "橋墩柱身澆置", unit: "m3", wbs: "civil" },
      { name: "橋墩帽梁澆置", unit: "m3", wbs: "civil" },
      { name: "沉箱基礎施作", unit: "m3", wbs: "civil" },
      { name: "支承墊安裝", unit: "m3", wbs: "civil" },
      { name: "預力梁製作", unit: "m3", wbs: "civil" },
      { name: "預力梁預力施拉", unit: "m3", wbs: "civil" },
      { name: "預力梁運輸", unit: "m3", wbs: "civil" },
      { name: "預力梁吊裝", unit: "m3", wbs: "civil" },
      { name: "鋼梁製作", unit: "t", wbs: "civil" },
      { name: "鋼梁運輸", unit: "t", wbs: "civil" },
      { name: "鋼梁吊裝", unit: "t", wbs: "civil" },
      { name: "鋼梁現場銲接", unit: "t", wbs: "civil" },
      { name: "節塊推進施作", unit: "m", wbs: "pipeline" },
      { name: "懸臂工法施作", unit: "m3", wbs: "civil" },
      { name: "支撐先進工法施作", unit: "m3", wbs: "civil" },
      { name: "橋面版模板架設", unit: "m2", wbs: "civil" },
      { name: "橋面版鋼筋綁紮", unit: "t", wbs: "civil" },
      { name: "橋面版混凝土澆置", unit: "m3", wbs: "civil" },
      { name: "橋面版防水層施作", unit: "m2", wbs: "civil" },
      { name: "橋面舖裝施作", unit: "m3", wbs: "civil" },
      { name: "伸縮縫安裝", unit: "m", wbs: "civil" },
      { name: "橋梁護欄施作", unit: "m", wbs: "civil" },
      { name: "橋梁排水設施施作", unit: "m3", wbs: "civil" },
      { name: "橋梁照明設施施作", unit: "m3", wbs: "electrical" },
      { name: "橋梁標誌設置", unit: "座", wbs: "civil" },
      { name: "橋梁載重試驗", unit: "式", wbs: "civil" },
      { name: "橋梁動力特性試驗", unit: "式", wbs: "civil" },
      { name: "既有橋梁拆除", unit: "式", wbs: "civil" },
      { name: "橋梁補強施作", unit: "m3", wbs: "civil" },
      { name: "支承更換", unit: "m3", wbs: "civil" },
      { name: "伸縮縫更換", unit: "m", wbs: "civil" },
      { name: "橋墩保護工施作", unit: "座", wbs: "civil" },
      { name: "橋梁塗裝施作", unit: "m3", wbs: "civil" },
      { name: "防蝕處理", unit: "m3", wbs: "civil" },
      { name: "橋名牌設置", unit: "式", wbs: "civil" },
    ],
  },
  {
    id: "tunnel",
    label: "隧道工程",
    keywords: [
      "隧道",
      "潛盾",
      "鑽掘",
      "環片",
      "襯砌",
      "洞口",
      "貫通",
      "岩栓",
    ],
    structures: [
      "洞口段",
      "隧道襯砌",
      "環片",
      "橫坑",
      "逃生通道",
      "仰拱",
    ],
    sequences: [
      "鑽炸法開挖",
      "潛盾機推進",
      "環片組裝",
      "背填灌漿施作",
      "噴凝土施作",
      "岩栓施作",
      "二次襯砌澆置",
    ],
    equipment: [
      "潛盾機",
      "全斷面鑽掘機",
      "鋼支保",
      "通風設施",
      "監控系統",
    ],
    provenance: "ai-pending-review",
    workItems: [
      { name: "洞口段整坡作業", unit: "m2", wbs: "civil" },
      { name: "洞口段擋土施作", unit: "m", wbs: "civil" },
      { name: "洞口段管幕施作", unit: "m", wbs: "pipeline" },
      { name: "洞口環片架設", unit: "m", wbs: "civil" },
      { name: "鑽炸法開挖", unit: "m3", wbs: "civil" },
      { name: "機械開挖", unit: "m3", wbs: "civil" },
      { name: "全斷面鑽掘機組裝", unit: "組", wbs: "mechanical" },
      { name: "全斷面鑽掘機掘進", unit: "m", wbs: "civil" },
      { name: "潛盾機組裝", unit: "組", wbs: "mechanical" },
      { name: "潛盾機推進", unit: "m", wbs: "pipeline" },
      { name: "潛盾環片組裝", unit: "m", wbs: "civil" },
      { name: "背填灌漿施作", unit: "m", wbs: "civil" },
      { name: "鋼支保架設", unit: "m", wbs: "civil" },
      { name: "噴凝土施作", unit: "m2", wbs: "civil" },
      { name: "岩栓施作", unit: "m", wbs: "civil" },
      { name: "鋼線網舖設", unit: "m", wbs: "civil" },
      { name: "先撐管施作", unit: "m", wbs: "pipeline" },
      { name: "前進灌漿施作", unit: "m", wbs: "civil" },
      { name: "超前鑽探", unit: "m", wbs: "civil" },
      { name: "地質弱面處理", unit: "m", wbs: "civil" },
      { name: "湧水處理", unit: "m", wbs: "civil" },
      { name: "排水管施作", unit: "m", wbs: "pipeline" },
      { name: "防水膜舖設", unit: "m2", wbs: "civil" },
      { name: "二次襯砌澆置", unit: "m3", wbs: "civil" },
      { name: "仰拱澆置", unit: "m3", wbs: "civil" },
      { name: "路床施作", unit: "m2", wbs: "civil" },
      { name: "隧道內舖面施作", unit: "m2", wbs: "civil" },
      { name: "隧道內排水溝施作", unit: "m", wbs: "pipeline" },
      { name: "通風設施安裝", unit: "m", wbs: "mechanical" },
      { name: "照明設施安裝", unit: "m", wbs: "electrical" },
      { name: "消防設施安裝", unit: "m", wbs: "mechanical" },
      { name: "監控系統安裝", unit: "式", wbs: "electrical" },
      { name: "逃生通道施作", unit: "m", wbs: "civil" },
      { name: "橫坑施作", unit: "m", wbs: "civil" },
      { name: "隧道貫通測量", unit: "式", wbs: "indirect" },
      { name: "隧道變形監測", unit: "m", wbs: "civil" },
    ],
  },
  {
    id: "port",
    label: "港灣與海岸工程",
    keywords: [
      "港",
      "碼頭",
      "防波堤",
      "海堤",
      "消波",
      "航道",
      "養灘",
      "離岸",
      "突堤",
      "浚深",
    ],
    structures: [
      "防波堤",
      "碼頭",
      "海堤",
      "離岸堤",
      "突堤",
      "棧橋",
      "浮動碼頭",
      "燈塔",
    ],
    sequences: [
      "基礎拋石",
      "消波塊安放",
      "沉箱拖航",
      "沉箱安放",
      "碼頭基樁打設",
      "疏浚作業",
      "抽砂養灘作業",
    ],
    equipment: [
      "消波塊",
      "護舷",
      "繫船柱",
      "海岸保護工",
      "航道標誌",
    ],
    provenance: "ai-pending-review",
    workItems: [
      { name: "海域地質調查", unit: "m3", wbs: "civil" },
      { name: "海床整理作業", unit: "月", wbs: "civil" },
      { name: "防波堤基礎拋石", unit: "m3", wbs: "civil" },
      { name: "防波堤堤心石舖放", unit: "m", wbs: "civil" },
      { name: "消波塊製作", unit: "m3", wbs: "civil" },
      { name: "消波塊安放", unit: "m3", wbs: "civil" },
      { name: "沉箱製作", unit: "座", wbs: "civil" },
      { name: "沉箱拖航", unit: "座", wbs: "civil" },
      { name: "沉箱安放", unit: "座", wbs: "civil" },
      { name: "沉箱填充", unit: "座", wbs: "civil" },
      { name: "上部結構澆置", unit: "m3", wbs: "civil" },
      { name: "胸牆施作", unit: "m3", wbs: "civil" },
      { name: "碼頭基樁打設", unit: "支", wbs: "civil" },
      { name: "碼頭帽梁澆置", unit: "m3", wbs: "civil" },
      { name: "碼頭面版澆置", unit: "m3", wbs: "civil" },
      { name: "碼頭護舷安裝", unit: "m3", wbs: "civil" },
      { name: "繫船柱安裝", unit: "m3", wbs: "civil" },
      { name: "碼頭爬梯設置", unit: "式", wbs: "civil" },
      { name: "碼頭排水施作", unit: "m", wbs: "civil" },
      { name: "棧橋式碼頭施作", unit: "m3", wbs: "civil" },
      { name: "浮動碼頭施作", unit: "m3", wbs: "civil" },
      { name: "浮防波堤設置", unit: "m", wbs: "civil" },
      { name: "海堤堤基施作", unit: "m", wbs: "civil" },
      { name: "海堤護面施作", unit: "m", wbs: "civil" },
      { name: "離岸堤施作", unit: "m", wbs: "civil" },
      { name: "突堤施作", unit: "m", wbs: "civil" },
      { name: "養灘工程施作", unit: "m3", wbs: "civil" },
      { name: "抽砂養灘作業", unit: "月", wbs: "civil" },
      { name: "疏浚作業", unit: "m3", wbs: "civil" },
      { name: "疏浚土方處理", unit: "m3", wbs: "civil" },
      { name: "航道浚深", unit: "m3", wbs: "civil" },
      { name: "航道標誌設置", unit: "座", wbs: "civil" },
      { name: "燈塔設施施作", unit: "m3", wbs: "civil" },
      { name: "海岸保護工施作", unit: "m3", wbs: "civil" },
      { name: "海岸植生施作", unit: "m2", wbs: "civil" },
    ],
  },
  {
    id: "pipeline",
    label: "管線工程",
    keywords: [
      "管線",
      "接管",
      "幹管",
      "分支管",
      "推進",
    ],
    structures: [
      "幹管",
      "分支管",
      "人孔",
      "接戶管",
    ],
    sequences: [
      "管線放樣",
      "管溝開挖",
      "管線埋設",
      "推進工法施作",
      "人孔施作",
      "回填夯實",
      "水壓試驗",
      "路面復舊",
    ],
    equipment: [
      "延性鑄鐵管",
      "閥類",
      "流量計",
    ],
    provenance: "ai-pending-review",
    workItems: [
      { name: "管線路線測量", unit: "式", wbs: "indirect" },
      { name: "管線位置探測", unit: "m", wbs: "pipeline" },
      { name: "既有管線調查", unit: "m", wbs: "pipeline" },
      { name: "交通維持設施設置", unit: "月", wbs: "safety" },
      { name: "路面切割", unit: "m2", wbs: "pipeline" },
      { name: "管溝開挖", unit: "m3", wbs: "pipeline" },
      { name: "管溝支撐架設", unit: "m", wbs: "pipeline" },
      { name: "管床整理", unit: "m", wbs: "pipeline" },
      { name: "管線基礎砂舖設", unit: "m3", wbs: "pipeline" },
      { name: "管材吊放", unit: "m", wbs: "pipeline" },
      { name: "管線接合作業", unit: "m", wbs: "pipeline" },
      { name: "管線包封混凝土", unit: "m3", wbs: "pipeline" },
      { name: "管溝回填", unit: "m3", wbs: "pipeline" },
      { name: "回填夯實試驗", unit: "m3", wbs: "civil" },
      { name: "路面臨時舖設", unit: "m2", wbs: "safety" },
      { name: "路面永久復舊", unit: "m2", wbs: "pipeline" },
      { name: "推進工作井施作", unit: "m", wbs: "pipeline" },
      { name: "推進管推進", unit: "m", wbs: "pipeline" },
      { name: "推進管接合", unit: "m", wbs: "pipeline" },
      { name: "推進導向測量", unit: "m", wbs: "indirect" },
      { name: "鑽掘導孔施作", unit: "m", wbs: "pipeline" },
      { name: "水平鑽掘拉管", unit: "m", wbs: "pipeline" },
      { name: "管線穿越河川施作", unit: "m", wbs: "pipeline" },
      { name: "管線穿越道路施作", unit: "m", wbs: "pipeline" },
      { name: "人孔基礎施作", unit: "m3", wbs: "pipeline" },
      { name: "預鑄人孔安裝", unit: "座", wbs: "pipeline" },
      { name: "現場澆置人孔施作", unit: "m3", wbs: "civil" },
      { name: "人孔蓋設置", unit: "座", wbs: "pipeline" },
      { name: "人孔內襯施作", unit: "m2", wbs: "pipeline" },
      { name: "接戶管施作", unit: "m", wbs: "pipeline" },
      { name: "清管作業", unit: "月", wbs: "pipeline" },
      { name: "管線內視檢查", unit: "m", wbs: "pipeline" },
      { name: "管線水壓試驗", unit: "式", wbs: "pipeline" },
      { name: "管線氣壓試驗", unit: "式", wbs: "pipeline" },
      { name: "管線洩漏檢測", unit: "m", wbs: "pipeline" },
    ],
  },
  {
    id: "mep",
    label: "機電與儀控工程",
    keywords: [
      "機電",
      "配電",
      "儀控",
      "監控",
      "電纜",
      "受電",
      "變壓器",
      "可程式控制器",
      "泵浦",
    ],
    structures: [
      "受電室",
      "配電盤",
      "馬達控制中心",
      "現場控制盤",
      "中央監控",
    ],
    sequences: [
      "電力電纜佈放",
      "接地系統測試",
      "絕緣耐壓試驗",
      "儀器迴路測試",
      "儀控系統整合測試",
    ],
    equipment: [
      "高壓配電盤",
      "變壓器",
      "不斷電系統",
      "變頻器",
      "可程式控制器",
      "人機介面",
      "壓力計",
      "液位計",
    ],
    provenance: "ai-pending-review",
    workItems: [
      { name: "電力受電室施作", unit: "組", wbs: "electrical" },
      { name: "高壓配電盤安裝", unit: "組", wbs: "electrical" },
      { name: "低壓配電盤安裝", unit: "組", wbs: "electrical" },
      { name: "變壓器安裝", unit: "組", wbs: "electrical" },
      { name: "發電機安裝", unit: "組", wbs: "electrical" },
      { name: "不斷電系統安裝", unit: "式", wbs: "electrical" },
      { name: "電容器設備安裝", unit: "組", wbs: "electrical" },
      { name: "匯流排施作", unit: "組", wbs: "electrical" },
      { name: "電纜線槽施作", unit: "m", wbs: "electrical" },
      { name: "電纜管路配置", unit: "m", wbs: "electrical" },
      { name: "電力電纜佈放", unit: "m", wbs: "electrical" },
      { name: "控制電纜佈放", unit: "m", wbs: "electrical" },
      { name: "接地銅棒打設", unit: "組", wbs: "electrical" },
      { name: "接地系統測試", unit: "式", wbs: "electrical" },
      { name: "避雷設施施作", unit: "組", wbs: "electrical" },
      { name: "絕緣耐壓試驗", unit: "式", wbs: "mechanical" },
      { name: "馬達控制中心安裝", unit: "組", wbs: "mechanical" },
      { name: "變頻器安裝", unit: "組", wbs: "mechanical" },
      { name: "現場控制盤安裝", unit: "組", wbs: "mechanical" },
      { name: "操作開關安裝", unit: "組", wbs: "electrical" },
      { name: "可程式控制器安裝", unit: "組", wbs: "mechanical" },
      { name: "人機介面建置", unit: "式", wbs: "mechanical" },
      { name: "中央監控軟體建置", unit: "式", wbs: "mechanical" },
      { name: "通訊網路建置", unit: "式", wbs: "electrical" },
      { name: "壓力計安裝", unit: "組", wbs: "mechanical" },
      { name: "液位計安裝", unit: "組", wbs: "mechanical" },
      { name: "溫度計安裝", unit: "組", wbs: "mechanical" },
      { name: "流量計安裝", unit: "組", wbs: "electrical" },
      { name: "水質儀安裝", unit: "組", wbs: "mechanical" },
      { name: "分析儀安裝", unit: "組", wbs: "mechanical" },
      { name: "儀器迴路測試", unit: "組", wbs: "electrical" },
      { name: "儀控系統整合測試", unit: "式", wbs: "electrical" },
      { name: "泵浦機組安裝", unit: "組", wbs: "mechanical" },
      { name: "泵浦基礎施作", unit: "m3", wbs: "mechanical" },
      { name: "管路支撐架施作", unit: "m", wbs: "pipeline" },
      { name: "閥類安裝", unit: "組", wbs: "mechanical" },
      { name: "風機安裝", unit: "組", wbs: "mechanical" },
      { name: "空調設備安裝", unit: "組", wbs: "mechanical" },
      { name: "吊車軌道施作", unit: "m", wbs: "mechanical" },
      { name: "設備防蝕塗裝", unit: "組", wbs: "mechanical" },
    ],
  },
  {
    id: "service",
    label: "委託專業服務",
    keywords: [
      "委託",
      "專業服務",
      "監造",
      "履約管理",
      "技術服務",
      "促參",
      "PCM",
    ],
    structures: [],
    sequences: [
      "計畫書審查",
      "施工計畫審查",
      "圖說審查",
      "工區巡查",
      "查核",
      "會議辦理",
      "月報製作",
      "結案報告製作",
    ],
    equipment: [],
    provenance: "ai-pending-review",
    workItems: [],
  },
];

/**
 * 公共工程施作契約普遍存在的管理類履約事項。
 *
 * 取自真實監造報告的章節結構 —— 那份報告本身就是一份應辦事項的執行紀錄：
 * 施工計畫送審有「表定提送日期」（契約訂的期限），送審後可能「審退」再
 * 「再次提送」；查驗缺失有改善期限；進度及品質檢討會議是週期性的
 * （該案已辦到第 23 次）；進度落後需提出改善對策。
 *
 * 重要：這是「常見型態」而非「必然義務」。提示詞會要求模型仍須在契約中
 * 找到對應條款才列入，找不到就不列 —— 否則會把慣例當成契約義務。
 */
export const CONSTRUCTION_MANAGEMENT_PATTERNS = [
  "定期進度及品質檢討會議（契約多訂每週或每月一次）",
  "施工計畫書分項提送審查（各分項工程施工前，契約訂有表定提送日期）",
  "品質計畫提送審查",
  "施工圖說提送審查",
  "材料設備送審（審查未通過者須於期限內再次提送）",
  "材料與設備進場檢（試）驗",
  "監造查驗缺失限期改善",
  "進度落後時提出落後原因分析及改善對策",
  "分項工程完工查驗與估驗計價",
  "職業安全衛生自主管理與教育訓練",
  "環境保護與工地污染防制",
  "竣工查驗與驗收",
  "保固期間之瑕疵改善",
];

/** 依領域取出知識；找不到回 null。 */
export function findDomain(id: string | null | undefined): DomainKnowledge | null {
  if (!id) return null;
  return DOMAINS.find((d) => d.id === id) ?? null;
}

/** 全部參考工程分項的總數（依名稱去重），供測試與說明使用。 */
export function totalWorkItems(): number {
  return new Set(DOMAINS.flatMap((d) => d.workItems.map((w) => w.name))).size;
}

/** 參考分項的名稱清單（供只需要名稱的呼叫端）。 */
export function workItemNames(domain: DomainKnowledge): string[] {
  return domain.workItems.map((w) => w.name);
}

/**
 * 依名稱查參考分項的單位與類別。
 *
 * 供解讀契約後回填：模型若讀出了分項名稱卻沒讀到單位，
 * 名稱恰好對得上參考清單時就用參考值，不必讓使用者逐項補。
 */
export function lookupReference(name: string): ReferenceWorkItem | null {
  const key = name.trim();
  if (!key) return null;
  for (const d of DOMAINS) {
    const hit = d.workItems.find((w) => w.name === key);
    if (hit) return hit;
  }
  return null;
}
